### ISSUE TITLE
0.8.1+ styles broken in "production" webpack setting

### ISSUE THREAD

**Issue by yinzara** [amarofashion/react-credit-cards#81] opened 2020-05-13 20:57 UTC
We have an odd defect when upgrading to 0.8.1+ (0.8.2 has same problem but 0.8.0 is fine) when using React mode "production" ("development" is fine).

The styles for the entire credit card appear to not be applied.  If I set the react mode to development everything works great, but when I set it to production, I get the following:
![Screen Shot 2020-05-13 at 1 54 04 PM](https://user-images.githubusercontent.com/671855/81864408-6e95ec80-9521-11ea-9141-3719584307cc.png)

It should look like this (what happens when I set mode to "development"):
![Screen Shot 2020-05-13 at 1 56 49 PM](https://user-images.githubusercontent.com/671855/81864518-9b4a0400-9521-11ea-8e67-f4686fd445a5.png)

**Comment by carlosrodrigues94** [comment] 2020-05-14 16:49
i'm suffering with the same problem

**Comment by cassiocardoso** [comment] 2020-05-16 08:26
Hi folks, do you think it's possible to provide a reproducible example on Code Sandbox or a GitHub repo? Thanks!

**Comment by gilbarbara** [comment] 2020-05-17 03:24
Hey,

Are you using the `scss` or `css` file?` How are you importing it?

I just created builds with css and scss imports and they worked properly.

**Comment by yinzara** [comment] 2020-05-17 19:29
`import "react-credit-cards/es/styles-compiled.css"`

**Comment by yinzara** [comment] 2020-05-17 21:37
I even tried:
`import "react-credit-cards/es/styles.scss"`

with the sass-loader but same result.

**Comment by gilbarbara** [comment] 2020-05-17 22:10
@yinzara 
It's impossible to know what's happening without viewing some code...

Are you using webpack to bundle your app?
Did you update any other dependencies such as css-loader?

As I said, I didn't have this problem with a fresh create-react-app installation.
Can you try that?

[s]

**Comment by yinzara** [comment] 2020-05-17 22:42
I'm totally stupid. :) I meant WEBPACK production mode.  Not React.

I'm using webpack and when setting the webpack "mode" to "production" instead of "development", we lose all styles.  

This only happened as of 0.8.1.  0.8.0 works perfectly fine.

**Comment by gilbarbara** [comment] 2020-05-18 01:37
If you can you share your webpack config and package.json, I can take a look.

But since it's working in a fresh create-react-app setup it's hard to debug. Can you please try that on your machine?

[s]

**Comment by benb1983** [comment] 2020-05-29 10:24
+1 same issue

**Comment by gilbarbara** [comment] 2020-05-31 15:37
@benb1983 Can you provide a codesandbox or similar?

**Comment by delacannon** [comment] 2020-06-04 13:33
The same issue is happening to me using gatsby after the build process. 

Here is a simple gatsby repo with the issue:
[https://github.com/delacannon/gatsby-rcc-test](https://github.com/delacannon/gatsby-rcc-test)

On `gatsby develop` everything looks great. 
On `gatsby build && gatsby serve` the styles are not applied. I tried both the compiled css and the sass.

**Comment by gilbarbara** [comment] 2020-06-04 14:04
@delacannon the build folder doesn't have any css file.
I'm not sure how gatsby do that, but without it, there's no way to style the component.

**Comment by delacannon** [comment] 2020-06-04 15:00
@gilbarbara In gatsby the styles added on gatsby-browser.js are bundled on the header and globally accesible. Using react-credit-cards v0.8.2 the specific styles disappear. On the other hand using react-credit-cards v0.7.0 the styles are bundled correctly.

![Screenshot 2020-06-04 at 16 47 12](https://user-images.githubusercontent.com/12370858/83773329-ae657500-a684-11ea-8ebf-4bf119ad834c.png)

**Comment by gilbarbara** [comment] 2020-06-04 15:18
Fixed in 0.8.3
It was the `sideEffects` flag in the package.json. 😱

Sorry about that!

**Closed by gilbarbara** 2020-06-04 15:18 UTC
Labels: waiting response

**Comment by gilbarbara** [comment] 2020-06-04 15:19
@delacannon Thanks for the reproducing repo! 👍🏻
